notifications:
  createIssues:
    repository: "yrodiere/quarkus-github-playground-lottery-reports"
buckets:
  triage:
    label: "triage/needs-triage"
    delay: PT0S
    timeout: PT5M
  maintenance:
    reproducer:
      label: "needs-reproducer"
      needed:
        delay: PT1M
        timeout: PT5M
      provided:
        delay: PT1M
        timeout: PT5M
    stale:
      delay: PT2M
      timeout: PT5M
participants:
  - username: "yrodiere"
    timezone: "Europe/Paris"
    triage:
      days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"]
      maxIssues: 3
    maintenance:
      labels: ["area/hibernate-orm", "area/hibernate-search"]
      days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"]
      reproducer:
        needed:
          maxIssues: 4
        provided:
          maxIssues: 2
      stale:
        maxIssues: 5
